### ISSUE TITLE
Automatically print addr2line for crash reports

### ISSUE THREAD

**Issue by cnlohr** [AEFeinstein/Swadge-IDF-5.0#47]
Would be really cool if addr2line could actually output what line it's on automatically by the printf tool

**Comment by AEFeinstein** [comment]
FWIW, when I'm investigating crashes on actual hardware I remove the handler from `CMakeLists.txt`:
```
# These have to appear here, otherwise, ninja ignores them.
idf_build_set_property(LINK_OPTIONS "-Wl,--wrap=esp_panic_handler" APPEND)
idf_build_set_property(LINK_OPTIONS "-Wl,--wrap=esp_panic_abort" APPEND)
```
And remove the USB printf redirect:
```
// Set the log to print with advanced_usb_write_log_printf()
esp_log_set_vprintf(advanced_usb_write_log_printf);
```
And then I debug over the UART pads on the back. ESP's default crash handler is just so good.

I'm going to close this since it doesn't look like its getting done this year. @cnlohr reopen this if it's still actively on your todo list.
